<?php
require_once 'tools.php';
header('Content-Type: application/json');
$data = json_decode(file_get_contents('php://input'), true);
$id = $data['orderId'];
$order = get_order($id);

$currencies = get_currencies();

$currency_from = get_currency_full($order['currency_from']);
$currency_to = get_currency_full($order['currency_to']);

$created_time = strtotime($order['created_at']); // Предполагаем, что в заказе есть поле created_at
$time_limit = 30 * 60; // 30 минут в секундах
$current_time = time();
$elapsed_time = $current_time - $created_time;
$time_to_end = max(0, $time_limit - $elapsed_time); // Не позволяем значению стать отрицательным
$status = format_status($order['status']);
$data_arr = [
	"order" => [
		"id"                                     => "67d5c1619bfd8",
		"buy_time"                               => "30",
		"time_to_end"                            => "122",
		"txid"                                   => "",
		"txid_in"                                => "",
		"status"                                 => "waiting_for_payment",
		"raw_status"                             => "processing",
		"aml_type"                               => "",
		"wallet_address_owner"                   => "",
		"rate_id"                                => "722812",
		"currency_from"                          => "BTC",
		"currency_from_name"                     => "Bitcoin (BTC)",
		"currency_from_best_code"                => "btc",
		"currency_from_code"                     => "BITGO_BTC",
		"currency_from_type"                     => "crypt",
		"currency_from_wallet_type"              => "1",
		"currency_to"                            => "RUB",
		"currency_to_best_code"                  => "sbprub",
		"currency_to_code"                       => "IVANPAY_SBP",
		"currency_to_name"                       => "СБП RUB",
		"currency_to_type"                       => "fiat",
		"currency_to_wallet_type"                => "140",
		"currency_to_network_name"               => "",
		"wallet_name_from"                       => "Кошелек Bitcoin",
		"wallet_name_to"                         => "Номер телефона",
		"minamount_from"                         => "0",
		"finished"                               => "0",
		"wallet_address"                         => "3763PtUB5iSVbbpoDWboc3nGN9KwQkkLbj",
		"f_wallet_address"                       => "",
		"phone_number"                           => "",
		"f_phone_number"                         => "",
		"client_wallet_address"                  => "+78232102400",
		"amount_from"                            => "0.00220454",
		"amount_to"                              => "15656",
		"f_amount_from"                          => "0.00220454",
		"f_amount_to"                            => "15 656",
		"qiwi_fee_in"                            => "0",
		"status_text"                            => "Ожидаем вашей оплаты",
		"payment_url"                            => "",
		"icon_currency_from"                     => "https://static.exhub.io/clients/images/currencies/BTC.svg",
		"icon_currency_to"                       => "https://static.exhub.io/clients/images/currencies/SBPRUB.svg",
		"confirmation"                           => "1",
		"tx_from"                                => "1",
		"tx_to"                                  => "",
		"link"                                   => "",
		"real_amount_from"                       => "0.00220454",
		"real_amount_to"                         => "15656",
		"course_now"                             => "7101708.29",
		"course_initial"                         => "7101708.29",
		"amount_recalc_cause"                    => "",
		"type"                                   => "",
		"close_date"                             => "01.01.1970",
		"close_time"                             => "00:00",
		"referer"                                => "others",
		"aml_currency_from"                      => "Y",
		"client_wallet_address_formatted"        => "+78232102400",
		"client_wallet_address_from"             => "",
		"client_wallet_address_from_last_digits" => "",
		"tag_to"                                 => "",
		"tag_to_is_default"                      => "1",
		"amount_from_fee"                        => "0.00220454",
		"f_amount_from_fee"                      => "0.00220454",
		"transactions"                           => [],
		"tag_from"                               => "",
		"buy_crypt"                              => "1",
		"tx_address_from"                        => "https://blockchair.com/bitcoin/transaction/",
		"tx_address_to"                          => "",
		"qrcode"                                 => "https://api-statics.exhub.io/qrcodes/67d5c1619bfd8.png",
		"qrcode_tag"                             => "",
		"f_real_amount_from"                     => "0.00220454",
		"f_real_amount_to"                       => "15 656",
		"f_course_now"                           => "7 101 708.29",
		"f_course_initial"                       => "7 101 708.29",
		"time_to_send_crypt"                     => "",
		"text_in"                                => "<p>Рекомендуем с целью ускорения прохождения транзакции, увеличить комиссию в системе Bitcoin. Актуальные комиссии можно посмотреть <a href=\"https://bitaps.com\" target=\"_blank\">здесь</a>.</p>",
		"text_out"                               => "",
		"forced_floating_course"                 => "N",
		"additional_commission"                  => "",
		"course"                                 => "7101708.2928865",
		"network"                                => "",
		"url"                                    => "https://exhub.io/order/d18e1bab7a12b52ff6412567bc2488c0?t=ohrQYd0ffMlFaV0H6zIA6UKngzUm0zBS5n9kNee0czJNSzdKOVuY9gzRSNmB6owtf7XJAB8EAIsTNoiBU2QjSilg60Ko0FiqUFAr8a5vJn1%2B4j2cIgmONILjMVU%3D&pay_status=true",
		"url_pm"                                 => "https://exhub.io/order/d18e1bab7a12b52ff6412567bc2488c0?t=PctA/XuezaTfFf0OnR/mrJ3Jm3E+kzrY60ymxcXNbvVQsE4U5DuOwC6in1L8cqD3zHh1CxTngyD2KVM30T9LqAcOcth/7GSyk7TyznY97I0GqAvzxocW5BnSrnk=&s=1",
		"fail_url"                               => "https://exhub.io/order/d18e1bab7a12b52ff6412567bc2488c0?t=TM3uBkZPzKLAK8kBejdJXVxm3pe5Ym07%2B3xuiApQ71hl%2B8h%2BnJURioFndSL05%2BqRYKK6Ieqc1pt7yyRSL8Q8BEkvT%2FzlsbL96Pqa%2FUgzY%2FIbm3wIO2cH4bTpXc8%3D",
		"fail_url_pm"                            => "https://exhub.io/order/d18e1bab7a12b52ff6412567bc2488c0?t=P1VwdDWxWLEDt34BsqLaxODsF0gExEDYODvf/SoLEvVU93OToqh5fplCLwh/4tI2OPp5Q8dmdv8RCpIZrmzEqQINXJlvRzxic57VD6oqzIxt6aVHsSxmYeyG5tI=",
		"need_to_confirm"                        => "0",
		"clientSidePaymentCompleted"             => "N",
		"show_bank_name"                         => "N",
		"f_course_from"                          => "",
		"f_course_to"                            => "",
		"is_paid"                                => "",
		"work_address"                           => "",
		"work_time"                              => "",
		"maincity"                               => "",
		"cash_mainform_text"                     => "",
		"bestchange_referer"                     => "N",
		"fail_aml"                               => "N",
		"incoming_pay_error"                     => "N",
		"bank_name"                              => "Сбербанк RUB",
		"is_sbp"                                 => "Y",
		"show_attention_eth"                     => "N",
		"show_attention_telegram_trc20"          => "N",
		"client_claim_pay_button"                => "N",
		"isWalletAmlCheckRequired"               => "N",
		"hasAdditionalSbpRequisites"             => "N",
		"isNeedCashReceipt"                      => "",
		"waitingCashReceiptAproval"              => ""
	]
    ];

$array = [
    "status" => 200,
    "data"   => [
        "order" => [
            "id"                                     => (string)$order['id'],
            "buy_time"                               => $currency_from['buy_time'],
            "time_to_end"                            => $time_to_end,
            "txid"                                   => "",
            "txid_in"                                => "",
            "status"                                 => $status['status'],
            "raw_status"                             => $status['raw_status'],
            "aml_type"                               => "",
            "wallet_address_owner"                   => "",
            "rate_id"                                => "722812",
            "currency_from"                          => $currency_from['best_code'],
            "currency_from_name"                     => $currency_from['name'],
            "currency_from_best_code"                => $currency_from['best_code'],
            "currency_from_code"                     => $currency_from['code'],
            "currency_from_type"                     => $currency_from['type'],
            "currency_from_wallet_type"              => $status['raw_status'] == 'new' ? "1" : "0",
            "currency_to"                            => $currency_to['best_code'],
            "currency_to_best_code"                  => $currency_to['best_code'],
            "currency_to_code"                       => $currency_to['code'],
            "currency_to_name"                       => $currency_to['name'],
            "currency_to_type"                       => $currency_to['type'],
            "currency_to_wallet_type"                => "140",
            "currency_to_network_name"               => $currency_to['network_name'] ?? "",
            "wallet_name_from"                       => $currency_from['wallet_name'],
            "wallet_name_to"                         => "Номер телефона",
            "minamount_from"                         => "0",
            "finished"                               => "0",
            "wallet_address"                         => "3EVGggQrckuJTamq49S91JsSB6YA2y5BZY",
            "f_wallet_address"                       => "",
            "phone_number"                           => "",
            "f_phone_number"                         => "",
            "client_wallet_address"                  => "+78232102400",
            "amount_from"                            => $order['amount_from'],
            "amount_to"                              => $order['amount_to'],
            "f_amount_from"                          => $order['amount_from'],
            "f_amount_to"                            => $order['amount_to'],
            "qiwi_fee_in"                            => $currency_from['qiwi_fee_in'] ?? "0",
            "status_text"                            => $status['status_text'],
            "payment_url"                            => "",
            "icon_currency_from"                     => $currency_from['icon_url'],
            "icon_currency_to"                       => $currency_to['icon_url'],
            "confirmation"                           => $currency_from['confirmations'],
            "tx_from"                                => "1",
            "tx_to"                                  => "",
            "link"                                   => "",
            "real_amount_from"                       => $order['amount_from'],
            "real_amount_to"                         => $order['amount_to'],
            "course_now"                             => $order['amount_from'],
            "course_initial"                         => $order['amount_from'],
            "amount_recalc_cause"                    => "",
            "type"                                   => "",
            "close_date"                             => "01.01.1970",
            "close_time"                             => "00:00",
            "referer"                                => "others",
            "aml_currency_from"                      => "Y",
            "client_wallet_address_formatted"        => "+78232102400",
            "client_wallet_address_from"             => "",
            "client_wallet_address_from_last_digits" => "",
            "tag_to"                                 => "",
            "tag_to_is_default"                      => "1",
            "amount_from_fee"                        => $order['amount_from'],
            "f_amount_from_fee"                      => $order['amount_from'],
            "transactions"                           => [],
            "tag_from"                               => $currency_from['tag_name'] ?? "",
            "buy_crypt"                              => "1",
            "tx_address_from"                        => "https://blockchair.com/bitcoin/transaction/",
            "tx_address_to"                          => "",
            "qrcode"                                 => "https://api-statics.exhub.io/qrcodes/67d5b13cda609.png",
            "qrcode_tag"                             => "",
            "f_real_amount_from"                     => $order['amount_from'],
            "f_real_amount_to"                       => $order['amount_to'],
            "f_course_now"                           => "7 079 946.76",
            "f_course_initial"                       => "7 079 946.76",
            "time_to_send_crypt"                     => "",
            "text_in"                                => $currency_from['text_in'],
            "text_out"                               => $currency_from['text_out'],
            "forced_floating_course"                 => "N",
            "additional_commission"                  => "",
            "course"                                 => "123123",
            "network"                                => $currency_from['network_name'] ?? "",
            "url"                                    => "https://".$_SERVER['HTTP_HOST']."/order/".$order['id']."?t=IBFa7Qa7fsSS4AOBlCvkjKKefU3%2B30WTQtPYzPIazefCjsV986fbQJoMGXqS351M15eA9n8IRVawgcdJeZIpd7cEZZlXQQ4LYFpbeRoEioDGz4P0D%2FkhyNVcUIQ%3D&pay_status=true",
            "url_pm"                                 => "https://".$_SERVER['HTTP_HOST']."/order/".$order['id']."?t=v4MII/d+hARi8wPm2UKcW4t2V+AFqFg2RGWDdXx+8aAE71bR71d5LlPhKu8DcGzZdhuFg5dYpuzsguNHEhR2qE968jH+Gi/Ip2gvtGVren+uY70hjI/YTwWzAbc=&s=1",
            "fail_url"                               => "https://".$_SERVER['HTTP_HOST']."/order/".$order['id']."?t=KgnLIRaMobRd%2BXDvxQeU3kUrgJadOr9tbhZSAZqnvCFb1v%2FTpYwHXCp%2B81%2FpBcLmB3Y%2FuuMKe2lJkGTVB6q1RqOY2OXV31qNviJXhR81Sqi0fhcaIrCFDhuU6kc%3D",
            "fail_url_pm"                            => "https://".$_SERVER['HTTP_HOST']."/order/".$order['id']."?t=NlIKE4GDBVmgYhlviztODEJPOwqpB3LZNyn86vKgsVH73LbDA6SbiGq4I0DZ8mdFeTvkVnum0dms7x3YpDtZgXIcN5M5ZNx1RQCNpb2oz7InoQOnHEF2LM2Z/QE=",
            "need_to_confirm"                        => $status['raw_status'] == 'new' ? "1" : "0",
            "clientSidePaymentCompleted"             => "N",
            "show_bank_name"                         => "N",
            "f_course_from"                          => "",
            "f_course_to"                            => "",
            "is_paid"                                => "",
            "work_address"                           => "",
            "work_time"                              => "",
            "maincity"                               => "",
            "cash_mainform_text"                     => "",
            "bestchange_referer"                     => "N",
            "fail_aml"                               => "",
            "incoming_pay_error"                     => "N",
            "bank_name"                              => "Сбербанк RUB",
            "is_sbp"                                 => "Y",
            "show_attention_eth"                     => "N",
            "show_attention_telegram_trc20"          => "N",
            "client_claim_pay_button"                => "N",
            "isWalletAmlCheckRequired"               => "N",
            "hasAdditionalSbpRequisites"             => "N",
            "isNeedCashReceipt"                      => "",
            "waitingCashReceiptAproval"              => "",
            "walletIsCard"                           => $currency_from['walletIsCard'] ?? "N",
            "isCash"                                 => $currency_from['isCash'] ?? "N",
            "isCNY"                                  => $currency_from['isCNY'] ?? "N",
            "address_regex"                          => $currency_from['address_regex'] ?? ""
        ]
    ]
];


echo json_encode($array);
